import Head from 'next/head'
import NavBar from '../components/NavBar'
import Hero from '../components/sections/Hero'
import LandingInfo from '../components/sections/LandingInfo'
import ReachOut from '../components/sections/ReachOut'
import NumberCrunch from '../components/sections/NumberCrunch'
import Details from '../components/sections/Details'
import Tokens from '../components/sections/Tokens'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Apeksha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <NavBar />
      <Hero />
      <LandingInfo />
      <ReachOut />
      <Details />
      <NumberCrunch />
      <Tokens />
    </div>
  )
}
